### ISSUE TITLE
Bold and Italic Markdown Support

### ISSUE THREAD

**Issue by no-stack-dub-sack** [no-stack-dub-sack/apexdox-vs-code#14]
Transform `__this__` to **this** and `_this_` to *this* in documentation comments (using asterisks style markdown would be potentially and needlessly complex due to the matching of doc comments which begin with **)

**Comment by sudhird7** [comment]
> Transform `__this__` to **this** and `_this_` to _this_ in documentation comments (using asterisks style markdown would be potentially and needlessly complex due to the matching of doc comments which begin with **)

Since the `<br>` tag is already supported, what would the lift be to support additional **_limited_** HTML elements like `<em>, <b>, and <strong>`?

**Comment by cemerson** [comment]
FWIW I just added a pull request on a similar note. I went with HTML tags vs markdown (in hindsight I kind of like Markdown better) but see the [pull request](https://github.com/no-stack-dub-sack/apexdox-vs-code/pull/57) (or the VSIS in my [fork](https://github.com/cemerson/apexdox-vs-code)) if you want to check it out. Just added bold, bullets and indented lists for now.

**Comment by no-stack-dub-sack** [comment]
@sudhird7 I agree, and will be accepting @cemerson's PR to include these features.

**Comment by sudhird7** [comment]
Thanks for the work, @cemerson and @no-stack-dub-sack !! Appreciate all the hard work. I hope one day I can contribute more.
