### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by oriolete** [no-stack-dub-sack/apexdox-vs-code#17]
Hi,

I suggest you a couple of thinks could be useful:

- Automatic, configurable Header on save
- Author and date on docs pages more visible
- Possibility of modification log like:

 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    3/12/2020  author  -author email    Initial Version

There an extension like yours called Salesforce Documenter (https://marketplace.visualstudio.com/items?itemName=HugoOM.sfdx-autoheader) with this options implemented.

Thanks and don't hesitaste to contact me for more details or test or help coding if necessary.

Cheers

**Comment by no-stack-dub-sack** [comment]
Hey @oriolete, thanks for reaching out! Yes, I saw this extension while I was researching the need for building this extension, however, as far as I can tell, the extension only helps with adding file headers, not with actually producing and documentation from the code.

That said, based on the number of downloads of the extension, it sounds like people may use this approach. Its certainly something we could consider adding to ApexDox if people will find it useful. 

Are you interested in submitting a PR to complete any of this?

**Comment by no-stack-dub-sack** [comment]
closing as stale, please feel free to reopen if you need additional assistance
