### ISSUE TITLE
Allow @return token (without 's')

### ISSUE THREAD

**Issue by berardo** [no-stack-dub-sack/apexdox-vs-code#19]
Hi Peter,

Thanks for this really useful plugin, I appreciate it.

I'm wondering if you found any particular issue with the token **@return**, as you renamed it to **@returns** ~1 year ago.

If your point was to solely make it consistent with TypeDoc (and consequently your Typescript docblocks), that'd make sense if Salesforce didn't seem to recommend **@return** as part of [ApexDoc](https://github.com/SalesforceFoundation/ApexDoc).

Moreover, PMD also takes ApexDoc as its source of truth of the documentation part for Apex code analysis, which makes ApexDox snippets for Apex methods always leaving us with the issue:

```
Missing ApexDoc @return (rule: Documentation-ApexDoc)apex pmdApexDoc
```

Is there any chance to revert it back to the singular version, or maybe accept both when html docs are generated?

FWIW, you can find PMD's ApexDocRule [here](https://github.com/pmd/pmd/blob/master/pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/documentation/ApexDocRule.java).

Happy to work on a PR if you want it.

Thank you

**Comment by no-stack-dub-sack** [comment]
Actually, I've been thinking about this recently myself. I'm super busy lately, but if you're willing to open a PR for this, we could get this change in ASAP. Let me know what you think.

**Comment by berardo** [comment]
Hi Peter,

I was not able to test it myself, but I prepared a[ pull request](https://github.com/no-stack-dub-sack/apexdox-vs-code/pull/20).

Thanks

**Comment by no-stack-dub-sack** [comment]
Great, thanks - sorry for the delay, was out of town. Will test and get back to you.
