### ISSUE TITLE
Suggestion: Allow forcing new-line in @description comments

### ISSUE THREAD

**Issue by jarodwsams** [no-stack-dub-sack/apexdox-vs-code#23]
I was just recently shown this add-in and I really appreciate the work. One thing that I think would be useful is the ability to force new-line and/or bullets in the @description tag. I've got an example below of where this would be helpful.

You'll note that the Class_Name_1 and _2 mentioned in the description block are also referenced as @see tags. I'm trying to annotate why those references are important.

```apex
/**
 * This class is used by Chatbot to create Dynamic Choice Menus for the customer to interact with.
 * The specific dynamic menu this class creates allows the customer to select the desired case that has already been created against their order,
 *   as specified by the `[variable]` value provided by the customer.
 * 
 * [ClassName_1] creates the Custom_Object__c records retrieved and displayed by this class
 * [ClassName_2] takes the selected Custom_Object__c record and extracts the [field]
 *
 * @author some schmuck
 * @group some group
 * @since some date
 * @see [ClassName_1]
 * @see [ClassName_2]
 */
```

![image](https://user-images.githubusercontent.com/22972834/99582049-2b707680-29a7-11eb-98b4-e7c4a0c1d7f0.png)

**Comment by no-stack-dub-sack** [comment]
Hi @jarodwsams, so sorry for the late reply on this. 

Actually, we do already have a way to force new lines inside any multi-line tag. See the [special tokens](https://github.com/no-stack-dub-sack/apexdox-vs-code#special-tokens) section of the README.

If you use a `<br />` tag inside the description, you can force a new line in between your comments.

Again, sorry for the late reply!
