### ISSUE TITLE
Q: How to modify the default comment snippets?

### ISSUE THREAD

**Issue by JackVeromeev** [no-stack-dub-sack/apexdox-vs-code#33]

**Comment by no-stack-dub-sack** [comment]
Can you please provide additional detail? If you mean the snippets that are generated by typing `/**` above an identifier or by using the `ApexDox: Stub Comment Block` command palette command, these cannot be modified by the end user except as configurable by [Comment Block Settings](https://github.com/no-stack-dub-sack/apexdox-vs-code#comment-block-settings) which are limited in what they can do. Other tags must be added manually after stubbing out a comment block.

**Comment by JackVeromeev** [comment]
Hi @no-stack-dub-sack!

Thank you for the answer, that's exactly what I wanted to know.

I use the plugin only for stubbing the docs in the code (just didn't face a project that require the static HTML docs yet). And due to the company's requirements, we must provide `@author` and `@copyright` tags, and we don't usually need `@since` so that I was curious if I can set up a list of the autogenerated tag list.

Thank you for the work you do and the support you provided!
