### ISSUE TITLE
The formatting of @author and @since does not meet the intended usage of these tags.

### ISSUE THREAD

**Issue by docbill** [no-stack-dub-sack/apexdox-vs-code#51]
```@author``` and ```@since``` are designed in JavaDoc so that one can maintain a version history...   e.g.

```
/**
 * @author Mark Smith <FOO@redhat.com>
 * @since 2013-01-04 Created
 * 
 * @author Bill C Riemers <BAR@redhat.com>
 * @since 2020-09-04 US270544 - Added comments, switched to a private set from a public map
 * @since 2022-09-08 Just a sample update
 */
```

This change log clearly indicates Mark Smith wrote this class in 2013-01-04 and it wasn't upaded again until 2020-09-04 by Bill C Riemers, and again I updated on 2022-09-08 as a sample of logging another change.

The generated output of;

```
Mark Smith <FOO@redhat.com> Bill C Riemers <BAR@redhat.com>
2013-01-04 Created 2020-09-04 US270544 - Added comments, switched to a private set from a public map 2022-09-08 Just a sample update
```

Is not really readable, as the since statements just all run together, and not nearly as useful, as you lose all information about who changed what.

**Comment by docbill** [comment]
I have created a pull request to fix this.  But I need to find directions on how to install and test my code...   Any reference as to the install and test procedure would be appreciated.

**Comment by docbill** [comment]
The pull-request https://github.com/no-stack-dub-sack/apexdox-vs-code/pull/55 is ready.  It looks like I don't have permissions to assign a reviewer.

**Comment by no-stack-dub-sack** [comment]
@docbill Sorry for the late reply - let me see if I have some docs on installing and testing, this has been a recurring issue especially since this project was originally built generations ago tech-time. If not, I can always test your code myself. there's no CI pipeline, all the tests are just run locally.
