### ISSUE TITLE
PMD Standard Rules and apexdox: @description 

### ISSUE THREAD

**Issue by Szandor72** [no-stack-dub-sack/apexdox-vs-code#53]
Is there a way to comply with https://pmd.github.io/latest/pmd_rules_apex_documentation.html?

Standard PMD rules require `@description` for apex docs, like this:

```java
/**
 * @description Hello World
 */
public class HelloWorld {
    /**
     * @description Bar
     * @return Bar
     */
    public Object bar() { return null; }
}
```

So far, I am adding @description manually.

**Comment by dschach** [comment]
This is covered in the README: [https://github.com/no-stack-dub-sack/apexdox-vs-code#comment-block-settings](https://github.com/no-stack-dub-sack/apexdox-vs-code#comment-block-settings)
