### ISSUE TITLE
Bug in recursive directories - links do not go to subfolder

### ISSUE THREAD

**Issue by dschach** [no-stack-dub-sack/apexdox-vs-code#73]
ApexDox accurately finds the Apex classes in subfolders when I only specify the parent folder (yay!) but the links to the classes themselves from each method do not point to the correct URL.

Example: 
- I have a folder `classes` and a subfolder `tests`. I put only the reference to `classes` in my `apexdox.yml` file
- ApexDox correctly includes all my classes in its list, and the page looks good, but...
- Clicking on the class name at the top of the page takes me to this link:
  ```
  <a
  target="_blank"
  rel="noopener noreferrer"
  title="Go to source"
  class="source-link"
  href="https://github.com/<owner>/<repo>/blob/main/force-app/main/default/classes/<ClassName>.cls#L13">
  <ClassName>							
  </a>
  ```
  but should take me to `main/default/classes/tests/

**Comment by no-stack-dub-sack** [comment]
@dschach  Thanks for the report - I'll look into this and fix it soon. Current workaround is just specifying both directories, right?

**Comment by dschach** [comment]
@no-stack-dub-sack Yes. Workaround is just doing what has always been done - or not specifying a path at all and only putting the parent directory in the config file. We lose the hyperlink, but that's not a huge loss.

**Comment by no-stack-dub-sack** [comment]
@dschach I know I'm not one to talk :-), but let me know if you have a chance to check out the PR for this and confirm that it works on your end.

**Comment by dschach** [comment]
Hi yes just back from vacation. I'll try it out.

**Comment by dschach** [comment]
Very sorry to say that it went janky on things. The URL for the file has something recursive in it. Here is a class header generated HTML:

```
<td class="doc-page">

          <div class="section">

            <h2 class="class-title top-level-type" id="ActionPlansDeleteMultipleAPExtension">

              <a target="_blank" rel="noopener noreferrer" title="Go to source" class="source-link" href="https://github.com/SalesforceLabs/ActionPlansV4/blob/main/sfdx-source/LabsActionPlans/main/default/classes/sfdx-source/LabsActionPlans/main/default/classes/ActionPlansDeleteMultipleAPExtension.cls#L28">
                ActionPlansDeleteMultipleAPExtension
              </a>
            </h2>
```
and here is a method
```
<div class="method public">
                  <h4 class="method-title " id="ActionPlansDeleteMultipleAPExtension.ActionPlansDeleteMultipleAPExtension">

                    <a target="_blank" rel="noopener noreferrer" title="Go to source" class="source-link" href="https://github.com/SalesforceLabs/ActionPlansV4/blob/main/sfdx-source/LabsActionPlans/main/default/classes/sfdx-source/LabsActionPlans/main/default/classes/ActionPlansDeleteMultipleAPExtension.cls#L40">
                      ActionPlansDeleteMultipleAPExtension(stdSetController)
                    </a>
                  </h4>
```
Looks like this may turn into a game of whack-a-mole.

I'm working in a branch of a fork, but if you want to see what I see, you can look at [https://github.com/dschach/ActionPlansV4/tree/docs/ApexDox-recursive](https://github.com/dschach/ActionPlansV4/tree/docs/ApexDox-recursive)

**Comment by no-stack-dub-sack** [comment]
Thanks @dschach! Moving this convo over to #74, see [my reply](https://github.com/no-stack-dub-sack/apexdox-vs-code/pull/74#issuecomment-1509175231) there.
