### ISSUE TITLE
Open Docs exception in latest release

### ISSUE THREAD

**Issue by rcmarti1** [no-stack-dub-sack/apexdox-vs-code#76]
Open Docs is no longer working. Extension Host logs the following TypeError:

```
TypeError: The "path" argument must be of type string. Received undefined
```
Looks like it may be in createDocServer where resolvedPath is coming back undefined.

Using default settings for the extension (also tried yaml and json). 

Version: 1.77.3 (user setup)
Commit: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
Date: 2023-04-12T09:16:02.548Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No

**Comment by no-stack-dub-sack** [comment]
Actually @rcmarti1, no worries. I found the source of the issue and will publish a release to fix shortly. Thanks for catching this!

**Comment by no-stack-dub-sack** [comment]
@rcmarti1 @dschach 2.0.1 has been published fixing this bug. Thanks!

**Comment by rcmarti1** [comment]
@no-stack-dub-sack  Just validated that it is working again. Thanks for the quick turnaround!
