### ISSUE TITLE
ENOENT: no such file or directory, scandir

### ISSUE THREAD

**Issue by pbornath** [no-stack-dub-sack/apexdox-vs-code#80]
I get the above error when I try to run apexdox. I am on a Mac running on MacOS Ventura. My understanding from the error would be that the code is looking for scandir but I am not finding it on the computer. Is there an assumption that it is available through a separate install or should be available generally?

**Comment by no-stack-dub-sack** [comment]
Hi @pbornath, admittedly this unfriendly error message can be improved, but my guess is that you have not configured apex dox, which uses a default configuration by default. There appears to be a bug with the default configuration settings which I can address soon.

In the meantime, check out the docs on how to configure apex dox's source and target directories. Be sure to use the [`${workspaceFolder}`](https://github.com/no-stack-dub-sack/apexdox-vs-code#the-workspacefolder-variable) variable in `apexdoc.engine.source.path`.

**Comment by no-stack-dub-sack** [comment]
@pbornath The bug has been fixed and will be released later today. Once you upgrade to the latest release you should be able to use the default settings. If the default folder does not exist, you'll get a helpful error message rather than a cryptic one like you received before.
